sudo: required
services:
  - docker
  
before_install:
  - docker build -t sibiss/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sibiss/react-test npm test -- --coverage
  
after_success:
  - docker build -t sibiss/multi-client ./client
  - docker build -t sibiss/multi-nginx ./nginx
  - docker build -t sibiss/multi-server ./server
  - docker build -t sibiss/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push sibiss/multi-client
  - docker push sibiss/multi-nginx
  - docker push sibiss/multi-server
  - docker push sibiss/multi-worker